### ISSUE TITLE
webrtc_adaptor.js to ES6 problem

### ISSUE THREAD

**Issue by arnoldcui** [ant-media/WebRTCApp4Enterprise#4]
We are trying the enterprise version of antMedia.
Here are some problem we meet.
1.Your library webrtc_adaptor.js is coded under the commonjs standard.But we are using ES6 & Typescript.Please let me know if you have any support for es6.
2.I try modify webrtc_adaptor.js to ES6 module,But still have problem.
The `getSenders()` function in`var senders = thiz.remotePeerConnection.getSenders()` shows me `getSenders is not a function`When I was streaming.
Because I need to find `streamId` In `turnOnLocalCamera` function.If there is the right way to get it ,please let me know.
thanks.

**Comment by mekya** [comment]
Hi @arnoldcui ,

Thank you for reaching out. Yeah you're right. There should be an update for that. Let me send a quick fix for that. 

Regards,
A. Oguz

**Comment by mekya** [comment]
I send a push commit for that. Please check it out

https://github.com/ant-media/WebRTCApp4Enterprise/commit/8b3f8b5d223ceb3f8102062e7b593241e3cbd499
